// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/islb/islb.proto

package islb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	media "github.com/pion/ion/pkg/proto/media"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindServiceRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Mid                  string   `protobuf:"bytes,2,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindServiceRequest) Reset()         { *m = FindServiceRequest{} }
func (m *FindServiceRequest) String() string { return proto.CompactTextString(m) }
func (*FindServiceRequest) ProtoMessage()    {}
func (*FindServiceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{0}
}

func (m *FindServiceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindServiceRequest.Unmarshal(m, b)
}
func (m *FindServiceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindServiceRequest.Marshal(b, m, deterministic)
}
func (m *FindServiceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindServiceRequest.Merge(m, src)
}
func (m *FindServiceRequest) XXX_Size() int {
	return xxx_messageInfo_FindServiceRequest.Size(m)
}
func (m *FindServiceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindServiceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindServiceRequest proto.InternalMessageInfo

func (m *FindServiceRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *FindServiceRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type FindServiceReply struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Service              string   `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Grpc                 string   `protobuf:"bytes,4,opt,name=grpc,proto3" json:"grpc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindServiceReply) Reset()         { *m = FindServiceReply{} }
func (m *FindServiceReply) String() string { return proto.CompactTextString(m) }
func (*FindServiceReply) ProtoMessage()    {}
func (*FindServiceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{1}
}

func (m *FindServiceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindServiceReply.Unmarshal(m, b)
}
func (m *FindServiceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindServiceReply.Marshal(b, m, deterministic)
}
func (m *FindServiceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindServiceReply.Merge(m, src)
}
func (m *FindServiceReply) XXX_Size() int {
	return xxx_messageInfo_FindServiceReply.Size(m)
}
func (m *FindServiceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_FindServiceReply.DiscardUnknown(m)
}

var xxx_messageInfo_FindServiceReply proto.InternalMessageInfo

func (m *FindServiceReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FindServiceReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FindServiceReply) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *FindServiceReply) GetGrpc() string {
	if m != nil {
		return m.Grpc
	}
	return ""
}

type StreamAddRequest struct {
	Minfo                *media.Info   `protobuf:"bytes,1,opt,name=minfo,proto3" json:"minfo,omitempty"`
	Uinfo                *UserMetadata `protobuf:"bytes,2,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
	Stream               *media.Stream `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StreamAddRequest) Reset()         { *m = StreamAddRequest{} }
func (m *StreamAddRequest) String() string { return proto.CompactTextString(m) }
func (*StreamAddRequest) ProtoMessage()    {}
func (*StreamAddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{2}
}

func (m *StreamAddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAddRequest.Unmarshal(m, b)
}
func (m *StreamAddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAddRequest.Marshal(b, m, deterministic)
}
func (m *StreamAddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAddRequest.Merge(m, src)
}
func (m *StreamAddRequest) XXX_Size() int {
	return xxx_messageInfo_StreamAddRequest.Size(m)
}
func (m *StreamAddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAddRequest proto.InternalMessageInfo

func (m *StreamAddRequest) GetMinfo() *media.Info {
	if m != nil {
		return m.Minfo
	}
	return nil
}

func (m *StreamAddRequest) GetUinfo() *UserMetadata {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

func (m *StreamAddRequest) GetStream() *media.Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

type StreamAddReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamAddReply) Reset()         { *m = StreamAddReply{} }
func (m *StreamAddReply) String() string { return proto.CompactTextString(m) }
func (*StreamAddReply) ProtoMessage()    {}
func (*StreamAddReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{3}
}

func (m *StreamAddReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamAddReply.Unmarshal(m, b)
}
func (m *StreamAddReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamAddReply.Marshal(b, m, deterministic)
}
func (m *StreamAddReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamAddReply.Merge(m, src)
}
func (m *StreamAddReply) XXX_Size() int {
	return xxx_messageInfo_StreamAddReply.Size(m)
}
func (m *StreamAddReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamAddReply.DiscardUnknown(m)
}

var xxx_messageInfo_StreamAddReply proto.InternalMessageInfo

type StreamRemoveRequest struct {
	Minfo                *media.Info `protobuf:"bytes,1,opt,name=minfo,proto3" json:"minfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StreamRemoveRequest) Reset()         { *m = StreamRemoveRequest{} }
func (m *StreamRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*StreamRemoveRequest) ProtoMessage()    {}
func (*StreamRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{4}
}

func (m *StreamRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRemoveRequest.Unmarshal(m, b)
}
func (m *StreamRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRemoveRequest.Marshal(b, m, deterministic)
}
func (m *StreamRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRemoveRequest.Merge(m, src)
}
func (m *StreamRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_StreamRemoveRequest.Size(m)
}
func (m *StreamRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRemoveRequest proto.InternalMessageInfo

func (m *StreamRemoveRequest) GetMinfo() *media.Info {
	if m != nil {
		return m.Minfo
	}
	return nil
}

type StreamRemoveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StreamRemoveReply) Reset()         { *m = StreamRemoveReply{} }
func (m *StreamRemoveReply) String() string { return proto.CompactTextString(m) }
func (*StreamRemoveReply) ProtoMessage()    {}
func (*StreamRemoveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{5}
}

func (m *StreamRemoveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StreamRemoveReply.Unmarshal(m, b)
}
func (m *StreamRemoveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StreamRemoveReply.Marshal(b, m, deterministic)
}
func (m *StreamRemoveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StreamRemoveReply.Merge(m, src)
}
func (m *StreamRemoveReply) XXX_Size() int {
	return xxx_messageInfo_StreamRemoveReply.Size(m)
}
func (m *StreamRemoveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StreamRemoveReply.DiscardUnknown(m)
}

var xxx_messageInfo_StreamRemoveReply proto.InternalMessageInfo

type GetPubsRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubsRequest) Reset()         { *m = GetPubsRequest{} }
func (m *GetPubsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPubsRequest) ProtoMessage()    {}
func (*GetPubsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{6}
}

func (m *GetPubsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubsRequest.Unmarshal(m, b)
}
func (m *GetPubsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubsRequest.Marshal(b, m, deterministic)
}
func (m *GetPubsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubsRequest.Merge(m, src)
}
func (m *GetPubsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPubsRequest.Size(m)
}
func (m *GetPubsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubsRequest proto.InternalMessageInfo

func (m *GetPubsRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *GetPubsRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type GetPubsReply struct {
	Pubs                 []*Pub   `protobuf:"bytes,2,rep,name=pubs,proto3" json:"pubs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPubsReply) Reset()         { *m = GetPubsReply{} }
func (m *GetPubsReply) String() string { return proto.CompactTextString(m) }
func (*GetPubsReply) ProtoMessage()    {}
func (*GetPubsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{7}
}

func (m *GetPubsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPubsReply.Unmarshal(m, b)
}
func (m *GetPubsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPubsReply.Marshal(b, m, deterministic)
}
func (m *GetPubsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPubsReply.Merge(m, src)
}
func (m *GetPubsReply) XXX_Size() int {
	return xxx_messageInfo_GetPubsReply.Size(m)
}
func (m *GetPubsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPubsReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetPubsReply proto.InternalMessageInfo

func (m *GetPubsReply) GetPubs() []*Pub {
	if m != nil {
		return m.Pubs
	}
	return nil
}

type JoinRequest struct {
	Rid                  string        `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string        `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Metadata             *UserMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{8}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *JoinRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *JoinRequest) GetMetadata() *UserMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type JoinReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinReply) Reset()         { *m = JoinReply{} }
func (m *JoinReply) String() string { return proto.CompactTextString(m) }
func (*JoinReply) ProtoMessage()    {}
func (*JoinReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{9}
}

func (m *JoinReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinReply.Unmarshal(m, b)
}
func (m *JoinReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinReply.Marshal(b, m, deterministic)
}
func (m *JoinReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinReply.Merge(m, src)
}
func (m *JoinReply) XXX_Size() int {
	return xxx_messageInfo_JoinReply.Size(m)
}
func (m *JoinReply) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinReply.DiscardUnknown(m)
}

var xxx_messageInfo_JoinReply proto.InternalMessageInfo

type LeaveRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveRequest) Reset()         { *m = LeaveRequest{} }
func (m *LeaveRequest) String() string { return proto.CompactTextString(m) }
func (*LeaveRequest) ProtoMessage()    {}
func (*LeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{10}
}

func (m *LeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveRequest.Unmarshal(m, b)
}
func (m *LeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveRequest.Marshal(b, m, deterministic)
}
func (m *LeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveRequest.Merge(m, src)
}
func (m *LeaveRequest) XXX_Size() int {
	return xxx_messageInfo_LeaveRequest.Size(m)
}
func (m *LeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveRequest proto.InternalMessageInfo

func (m *LeaveRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *LeaveRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type LeaveReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaveReply) Reset()         { *m = LeaveReply{} }
func (m *LeaveReply) String() string { return proto.CompactTextString(m) }
func (*LeaveReply) ProtoMessage()    {}
func (*LeaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{11}
}

func (m *LeaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaveReply.Unmarshal(m, b)
}
func (m *LeaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaveReply.Marshal(b, m, deterministic)
}
func (m *LeaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaveReply.Merge(m, src)
}
func (m *LeaveReply) XXX_Size() int {
	return xxx_messageInfo_LeaveReply.Size(m)
}
func (m *LeaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_LeaveReply proto.InternalMessageInfo

type GetStreamRequest struct {
	Minfo                *media.Info `protobuf:"bytes,1,opt,name=minfo,proto3" json:"minfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetStreamRequest) Reset()         { *m = GetStreamRequest{} }
func (m *GetStreamRequest) String() string { return proto.CompactTextString(m) }
func (*GetStreamRequest) ProtoMessage()    {}
func (*GetStreamRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{12}
}

func (m *GetStreamRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamRequest.Unmarshal(m, b)
}
func (m *GetStreamRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamRequest.Marshal(b, m, deterministic)
}
func (m *GetStreamRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamRequest.Merge(m, src)
}
func (m *GetStreamRequest) XXX_Size() int {
	return xxx_messageInfo_GetStreamRequest.Size(m)
}
func (m *GetStreamRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamRequest proto.InternalMessageInfo

func (m *GetStreamRequest) GetMinfo() *media.Info {
	if m != nil {
		return m.Minfo
	}
	return nil
}

type GetStreamReply struct {
	Stream               *media.Stream `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetStreamReply) Reset()         { *m = GetStreamReply{} }
func (m *GetStreamReply) String() string { return proto.CompactTextString(m) }
func (*GetStreamReply) ProtoMessage()    {}
func (*GetStreamReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{13}
}

func (m *GetStreamReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetStreamReply.Unmarshal(m, b)
}
func (m *GetStreamReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetStreamReply.Marshal(b, m, deterministic)
}
func (m *GetStreamReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetStreamReply.Merge(m, src)
}
func (m *GetStreamReply) XXX_Size() int {
	return xxx_messageInfo_GetStreamReply.Size(m)
}
func (m *GetStreamReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetStreamReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetStreamReply proto.InternalMessageInfo

func (m *GetStreamReply) GetStream() *media.Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

type BroadcastRequest struct {
	Rid                  string   `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Payload              []byte   `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastRequest) Reset()         { *m = BroadcastRequest{} }
func (m *BroadcastRequest) String() string { return proto.CompactTextString(m) }
func (*BroadcastRequest) ProtoMessage()    {}
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{14}
}

func (m *BroadcastRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastRequest.Unmarshal(m, b)
}
func (m *BroadcastRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastRequest.Marshal(b, m, deterministic)
}
func (m *BroadcastRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastRequest.Merge(m, src)
}
func (m *BroadcastRequest) XXX_Size() int {
	return xxx_messageInfo_BroadcastRequest.Size(m)
}
func (m *BroadcastRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastRequest proto.InternalMessageInfo

func (m *BroadcastRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *BroadcastRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *BroadcastRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type BroadcastReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BroadcastReply) Reset()         { *m = BroadcastReply{} }
func (m *BroadcastReply) String() string { return proto.CompactTextString(m) }
func (*BroadcastReply) ProtoMessage()    {}
func (*BroadcastReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{15}
}

func (m *BroadcastReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BroadcastReply.Unmarshal(m, b)
}
func (m *BroadcastReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BroadcastReply.Marshal(b, m, deterministic)
}
func (m *BroadcastReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BroadcastReply.Merge(m, src)
}
func (m *BroadcastReply) XXX_Size() int {
	return xxx_messageInfo_BroadcastReply.Size(m)
}
func (m *BroadcastReply) XXX_DiscardUnknown() {
	xxx_messageInfo_BroadcastReply.DiscardUnknown(m)
}

var xxx_messageInfo_BroadcastReply proto.InternalMessageInfo

type UserMetadata struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserMetadata) Reset()         { *m = UserMetadata{} }
func (m *UserMetadata) String() string { return proto.CompactTextString(m) }
func (*UserMetadata) ProtoMessage()    {}
func (*UserMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{16}
}

func (m *UserMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserMetadata.Unmarshal(m, b)
}
func (m *UserMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserMetadata.Marshal(b, m, deterministic)
}
func (m *UserMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserMetadata.Merge(m, src)
}
func (m *UserMetadata) XXX_Size() int {
	return xxx_messageInfo_UserMetadata.Size(m)
}
func (m *UserMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_UserMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_UserMetadata proto.InternalMessageInfo

func (m *UserMetadata) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserInfo struct {
	Dc                   string   `protobuf:"bytes,1,opt,name=dc,proto3" json:"dc,omitempty"`
	Rid                  string   `protobuf:"bytes,2,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{17}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *UserInfo) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *UserInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type NodeInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeInfo) Reset()         { *m = NodeInfo{} }
func (m *NodeInfo) String() string { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()    {}
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{18}
}

func (m *NodeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeInfo.Unmarshal(m, b)
}
func (m *NodeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeInfo.Marshal(b, m, deterministic)
}
func (m *NodeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeInfo.Merge(m, src)
}
func (m *NodeInfo) XXX_Size() int {
	return xxx_messageInfo_NodeInfo.Size(m)
}
func (m *NodeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NodeInfo proto.InternalMessageInfo

func (m *NodeInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NodeInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NodeInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type Pub struct {
	Minfo                *media.Info   `protobuf:"bytes,1,opt,name=minfo,proto3" json:"minfo,omitempty"`
	Uinfo                *UserMetadata `protobuf:"bytes,2,opt,name=uinfo,proto3" json:"uinfo,omitempty"`
	Stream               *media.Stream `protobuf:"bytes,3,opt,name=stream,proto3" json:"stream,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Pub) Reset()         { *m = Pub{} }
func (m *Pub) String() string { return proto.CompactTextString(m) }
func (*Pub) ProtoMessage()    {}
func (*Pub) Descriptor() ([]byte, []int) {
	return fileDescriptor_9898ba65d43d8354, []int{19}
}

func (m *Pub) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pub.Unmarshal(m, b)
}
func (m *Pub) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pub.Marshal(b, m, deterministic)
}
func (m *Pub) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pub.Merge(m, src)
}
func (m *Pub) XXX_Size() int {
	return xxx_messageInfo_Pub.Size(m)
}
func (m *Pub) XXX_DiscardUnknown() {
	xxx_messageInfo_Pub.DiscardUnknown(m)
}

var xxx_messageInfo_Pub proto.InternalMessageInfo

func (m *Pub) GetMinfo() *media.Info {
	if m != nil {
		return m.Minfo
	}
	return nil
}

func (m *Pub) GetUinfo() *UserMetadata {
	if m != nil {
		return m.Uinfo
	}
	return nil
}

func (m *Pub) GetStream() *media.Stream {
	if m != nil {
		return m.Stream
	}
	return nil
}

func init() {
	proto.RegisterType((*FindServiceRequest)(nil), "islb.FindServiceRequest")
	proto.RegisterType((*FindServiceReply)(nil), "islb.FindServiceReply")
	proto.RegisterType((*StreamAddRequest)(nil), "islb.StreamAddRequest")
	proto.RegisterType((*StreamAddReply)(nil), "islb.StreamAddReply")
	proto.RegisterType((*StreamRemoveRequest)(nil), "islb.StreamRemoveRequest")
	proto.RegisterType((*StreamRemoveReply)(nil), "islb.StreamRemoveReply")
	proto.RegisterType((*GetPubsRequest)(nil), "islb.GetPubsRequest")
	proto.RegisterType((*GetPubsReply)(nil), "islb.GetPubsReply")
	proto.RegisterType((*JoinRequest)(nil), "islb.JoinRequest")
	proto.RegisterType((*JoinReply)(nil), "islb.JoinReply")
	proto.RegisterType((*LeaveRequest)(nil), "islb.LeaveRequest")
	proto.RegisterType((*LeaveReply)(nil), "islb.LeaveReply")
	proto.RegisterType((*GetStreamRequest)(nil), "islb.GetStreamRequest")
	proto.RegisterType((*GetStreamReply)(nil), "islb.GetStreamReply")
	proto.RegisterType((*BroadcastRequest)(nil), "islb.BroadcastRequest")
	proto.RegisterType((*BroadcastReply)(nil), "islb.BroadcastReply")
	proto.RegisterType((*UserMetadata)(nil), "islb.UserMetadata")
	proto.RegisterType((*UserInfo)(nil), "islb.UserInfo")
	proto.RegisterType((*NodeInfo)(nil), "islb.NodeInfo")
	proto.RegisterType((*Pub)(nil), "islb.Pub")
}

func init() { proto.RegisterFile("pkg/proto/islb/islb.proto", fileDescriptor_9898ba65d43d8354) }

var fileDescriptor_9898ba65d43d8354 = []byte{
	// 641 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x5b, 0x6b, 0x13, 0x41,
	0x14, 0x6e, 0xb2, 0xdb, 0x4b, 0xce, 0xc6, 0xba, 0x9d, 0x16, 0xdd, 0xae, 0x08, 0x75, 0x50, 0xe8,
	0x83, 0x26, 0x10, 0x2d, 0x0a, 0x82, 0xd8, 0x20, 0x96, 0x4a, 0x95, 0xb0, 0xc5, 0x17, 0xdf, 0x66,
	0x77, 0xa6, 0x75, 0x30, 0x7b, 0x71, 0x2f, 0x85, 0xfc, 0x01, 0x7f, 0xa5, 0x3f, 0x46, 0xe6, 0xb6,
	0x97, 0xa4, 0x68, 0xfa, 0xe4, 0x43, 0x96, 0xb3, 0x67, 0xbe, 0xef, 0x9c, 0x39, 0xdf, 0xec, 0x37,
	0x81, 0xc3, 0xec, 0xc7, 0xf5, 0x38, 0xcb, 0xd3, 0x32, 0x1d, 0xf3, 0x62, 0x1e, 0xca, 0xc7, 0x48,
	0xbe, 0x23, 0x5b, 0xc4, 0xfe, 0xa3, 0x06, 0x10, 0x33, 0xca, 0x89, 0x7a, 0x2a, 0x08, 0x7e, 0x0f,
	0xe8, 0x23, 0x4f, 0xe8, 0x25, 0xcb, 0x6f, 0x78, 0xc4, 0x02, 0xf6, 0xb3, 0x62, 0x45, 0x89, 0x3c,
	0xd8, 0x2e, 0x54, 0xc6, 0xeb, 0x1d, 0xf5, 0x8e, 0x07, 0x81, 0x79, 0x45, 0x2e, 0x58, 0x31, 0xa7,
	0x5e, 0x5f, 0x66, 0x45, 0x88, 0x29, 0xb8, 0x9d, 0x0a, 0xd9, 0x7c, 0x81, 0x76, 0xa1, 0xcf, 0xa9,
	0xa6, 0xf6, 0x39, 0x45, 0x08, 0xec, 0x84, 0xc4, 0x4c, 0xd3, 0x64, 0xdc, 0xee, 0x61, 0x75, 0x7b,
	0x20, 0xb0, 0xaf, 0xf3, 0x2c, 0xf2, 0x6c, 0x85, 0x16, 0x31, 0xfe, 0xd5, 0x03, 0xf7, 0xb2, 0xcc,
	0x19, 0x89, 0x4f, 0x29, 0x35, 0xdb, 0x7c, 0x02, 0x9b, 0x31, 0x4f, 0xae, 0x52, 0xd9, 0xc9, 0x99,
	0x38, 0x23, 0x35, 0xd9, 0x79, 0x72, 0x95, 0x06, 0x6a, 0x05, 0x1d, 0xc3, 0x66, 0x25, 0x21, 0x7d,
	0x09, 0x41, 0x23, 0x29, 0xcf, 0xd7, 0x82, 0xe5, 0x9f, 0x59, 0x49, 0x28, 0x29, 0x49, 0xa0, 0x00,
	0xe8, 0x19, 0x6c, 0x15, 0xb2, 0x81, 0xdc, 0x8e, 0x33, 0xb9, 0xa7, 0xab, 0xa9, 0xae, 0x81, 0x5e,
	0xc4, 0x2e, 0xec, 0xb6, 0xf6, 0x91, 0xcd, 0x17, 0xf8, 0x0d, 0xec, 0x6b, 0x0c, 0x8b, 0xd3, 0x1b,
	0xb6, 0xfe, 0xe6, 0xf0, 0x3e, 0xec, 0x75, 0x99, 0xa2, 0xdc, 0x2b, 0xd8, 0x3d, 0x63, 0xe5, 0xac,
	0x0a, 0x0b, 0x53, 0xc9, 0x05, 0x2b, 0xaf, 0xe5, 0x14, 0xa1, 0xc8, 0x54, 0xcd, 0x29, 0x54, 0x9c,
	0xe2, 0x17, 0x30, 0xac, 0x59, 0xe2, 0x04, 0x1e, 0x83, 0x9d, 0x55, 0x61, 0xe1, 0xf5, 0x8f, 0xac,
	0x63, 0x67, 0x32, 0x50, 0x63, 0xcf, 0xaa, 0x30, 0x90, 0x69, 0x4c, 0xc0, 0xf9, 0x94, 0xf2, 0xe4,
	0x0e, 0x1d, 0xd0, 0x08, 0x76, 0x62, 0x2d, 0x99, 0x56, 0xe8, 0x36, 0x31, 0x6b, 0x0c, 0x76, 0x60,
	0xa0, 0x5a, 0x88, 0xa1, 0x26, 0x30, 0xbc, 0x60, 0xa4, 0x11, 0x67, 0x9d, 0x91, 0x86, 0x00, 0x9a,
	0x23, 0x2a, 0x9c, 0x80, 0x7b, 0xc6, 0x4a, 0x23, 0xd7, 0xda, 0x12, 0xbf, 0x96, 0x6a, 0x1a, 0x9a,
	0x50, 0xa6, 0x39, 0xe7, 0xde, 0xdf, 0xce, 0x79, 0x06, 0xee, 0x34, 0x4f, 0x09, 0x8d, 0x48, 0x51,
	0xde, 0x45, 0x26, 0x0f, 0xb6, 0x33, 0xb2, 0x98, 0xa7, 0x84, 0x4a, 0x95, 0x86, 0x81, 0x79, 0x15,
	0x5f, 0x4e, 0xab, 0xa2, 0x98, 0x09, 0xc3, 0xb0, 0x2d, 0x5e, 0x6d, 0x93, 0x5e, 0x63, 0x13, 0xfc,
	0x0e, 0x76, 0x04, 0x46, 0xcc, 0x24, 0x6c, 0x45, 0x23, 0x63, 0x2b, 0x1a, 0x99, 0xfd, 0xf4, 0x57,
	0xf6, 0x63, 0x35, 0x2a, 0x4e, 0x61, 0xe7, 0x4b, 0x4a, 0x99, 0xe1, 0xff, 0xd3, 0x96, 0x08, 0xec,
	0x72, 0x91, 0x19, 0x4f, 0xca, 0x18, 0x2f, 0xc0, 0x9a, 0x55, 0xe1, 0xff, 0xb0, 0xdb, 0xe4, 0xb7,
	0x05, 0xf6, 0xf9, 0xe5, 0xc5, 0x14, 0x9d, 0x82, 0xd3, 0xba, 0x66, 0x90, 0xa7, 0x2a, 0xaf, 0xde,
	0x5d, 0xfe, 0x83, 0x5b, 0x56, 0x84, 0xd8, 0x1b, 0xe8, 0x2d, 0x0c, 0x6a, 0xeb, 0x22, 0x0d, 0x5b,
	0xbe, 0x53, 0xfc, 0x83, 0x95, 0xbc, 0x22, 0x7f, 0x80, 0x61, 0xdb, 0xab, 0xe8, 0xb0, 0x8d, 0xeb,
	0x38, 0xdf, 0x7f, 0x78, 0xdb, 0x92, 0xaa, 0x72, 0x02, 0xdb, 0xda, 0xa6, 0x48, 0x37, 0xea, 0x7a,
	0xdd, 0x47, 0x4b, 0x59, 0x45, 0x7b, 0x0e, 0xb6, 0xf0, 0x12, 0xda, 0x53, 0xab, 0x2d, 0xeb, 0xfa,
	0xf7, 0xdb, 0x29, 0x85, 0x1e, 0xc3, 0xa6, 0x34, 0x0e, 0xd2, 0xc5, 0xda, 0xce, 0xf3, 0xdd, 0x4e,
	0xae, 0x16, 0xa6, 0x36, 0x89, 0x11, 0x66, 0xd9, 0x6c, 0xfe, 0xc1, 0x4a, 0xbe, 0x26, 0xd7, 0x9f,
	0xb5, 0x21, 0x2f, 0x3b, 0xc7, 0x90, 0x97, 0xbe, 0xff, 0x8d, 0xe9, 0xd3, 0x6f, 0xf8, 0x9a, 0x97,
	0xdf, 0xab, 0x70, 0x14, 0xa5, 0xf1, 0x38, 0xe3, 0x69, 0x32, 0x16, 0xbf, 0xee, 0x5f, 0x5a, 0xb8,
	0x25, 0xe3, 0x97, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x36, 0x0a, 0xad, 0xb3, 0xeb, 0x06, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ISLBClient is the client API for ISLB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ISLBClient interface {
	FindService(ctx context.Context, in *FindServiceRequest, opts ...grpc.CallOption) (*FindServiceReply, error)
	StreamAdd(ctx context.Context, in *StreamAddRequest, opts ...grpc.CallOption) (*StreamAddReply, error)
	StreamRemove(ctx context.Context, in *StreamRemoveRequest, opts ...grpc.CallOption) (*StreamRemoveReply, error)
	GetPubs(ctx context.Context, in *GetPubsRequest, opts ...grpc.CallOption) (*GetPubsReply, error)
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error)
	Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveReply, error)
	GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamReply, error)
	Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastReply, error)
}

type iSLBClient struct {
	cc *grpc.ClientConn
}

func NewISLBClient(cc *grpc.ClientConn) ISLBClient {
	return &iSLBClient{cc}
}

func (c *iSLBClient) FindService(ctx context.Context, in *FindServiceRequest, opts ...grpc.CallOption) (*FindServiceReply, error) {
	out := new(FindServiceReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/FindService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) StreamAdd(ctx context.Context, in *StreamAddRequest, opts ...grpc.CallOption) (*StreamAddReply, error) {
	out := new(StreamAddReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/StreamAdd", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) StreamRemove(ctx context.Context, in *StreamRemoveRequest, opts ...grpc.CallOption) (*StreamRemoveReply, error) {
	out := new(StreamRemoveReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/StreamRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) GetPubs(ctx context.Context, in *GetPubsRequest, opts ...grpc.CallOption) (*GetPubsReply, error) {
	out := new(GetPubsReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/GetPubs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinReply, error) {
	out := new(JoinReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) Leave(ctx context.Context, in *LeaveRequest, opts ...grpc.CallOption) (*LeaveReply, error) {
	out := new(LeaveReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/Leave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) GetStream(ctx context.Context, in *GetStreamRequest, opts ...grpc.CallOption) (*GetStreamReply, error) {
	out := new(GetStreamReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/GetStream", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iSLBClient) Broadcast(ctx context.Context, in *BroadcastRequest, opts ...grpc.CallOption) (*BroadcastReply, error) {
	out := new(BroadcastReply)
	err := c.cc.Invoke(ctx, "/islb.ISLB/Broadcast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ISLBServer is the server API for ISLB service.
type ISLBServer interface {
	FindService(context.Context, *FindServiceRequest) (*FindServiceReply, error)
	StreamAdd(context.Context, *StreamAddRequest) (*StreamAddReply, error)
	StreamRemove(context.Context, *StreamRemoveRequest) (*StreamRemoveReply, error)
	GetPubs(context.Context, *GetPubsRequest) (*GetPubsReply, error)
	Join(context.Context, *JoinRequest) (*JoinReply, error)
	Leave(context.Context, *LeaveRequest) (*LeaveReply, error)
	GetStream(context.Context, *GetStreamRequest) (*GetStreamReply, error)
	Broadcast(context.Context, *BroadcastRequest) (*BroadcastReply, error)
}

// UnimplementedISLBServer can be embedded to have forward compatible implementations.
type UnimplementedISLBServer struct {
}

func (*UnimplementedISLBServer) FindService(ctx context.Context, req *FindServiceRequest) (*FindServiceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindService not implemented")
}
func (*UnimplementedISLBServer) StreamAdd(ctx context.Context, req *StreamAddRequest) (*StreamAddReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamAdd not implemented")
}
func (*UnimplementedISLBServer) StreamRemove(ctx context.Context, req *StreamRemoveRequest) (*StreamRemoveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StreamRemove not implemented")
}
func (*UnimplementedISLBServer) GetPubs(ctx context.Context, req *GetPubsRequest) (*GetPubsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPubs not implemented")
}
func (*UnimplementedISLBServer) Join(ctx context.Context, req *JoinRequest) (*JoinReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Join not implemented")
}
func (*UnimplementedISLBServer) Leave(ctx context.Context, req *LeaveRequest) (*LeaveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Leave not implemented")
}
func (*UnimplementedISLBServer) GetStream(ctx context.Context, req *GetStreamRequest) (*GetStreamReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStream not implemented")
}
func (*UnimplementedISLBServer) Broadcast(ctx context.Context, req *BroadcastRequest) (*BroadcastReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Broadcast not implemented")
}

func RegisterISLBServer(s *grpc.Server, srv ISLBServer) {
	s.RegisterService(&_ISLB_serviceDesc, srv)
}

func _ISLB_FindService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).FindService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/FindService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).FindService(ctx, req.(*FindServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_StreamAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).StreamAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/StreamAdd",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).StreamAdd(ctx, req.(*StreamAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_StreamRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).StreamRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/StreamRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).StreamRemove(ctx, req.(*StreamRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_GetPubs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPubsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).GetPubs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/GetPubs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).GetPubs(ctx, req.(*GetPubsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_Leave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).Leave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/Leave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).Leave(ctx, req.(*LeaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_GetStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).GetStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/GetStream",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).GetStream(ctx, req.(*GetStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ISLB_Broadcast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BroadcastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ISLBServer).Broadcast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/islb.ISLB/Broadcast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ISLBServer).Broadcast(ctx, req.(*BroadcastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ISLB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "islb.ISLB",
	HandlerType: (*ISLBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindService",
			Handler:    _ISLB_FindService_Handler,
		},
		{
			MethodName: "StreamAdd",
			Handler:    _ISLB_StreamAdd_Handler,
		},
		{
			MethodName: "StreamRemove",
			Handler:    _ISLB_StreamRemove_Handler,
		},
		{
			MethodName: "GetPubs",
			Handler:    _ISLB_GetPubs_Handler,
		},
		{
			MethodName: "Join",
			Handler:    _ISLB_Join_Handler,
		},
		{
			MethodName: "Leave",
			Handler:    _ISLB_Leave_Handler,
		},
		{
			MethodName: "GetStream",
			Handler:    _ISLB_GetStream_Handler,
		},
		{
			MethodName: "Broadcast",
			Handler:    _ISLB_Broadcast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/islb/islb.proto",
}
