// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/media/media.proto

package media

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Info struct {
	Dc                   string   `protobuf:"bytes,1,opt,name=dc,proto3" json:"dc,omitempty"`
	Nid                  string   `protobuf:"bytes,2,opt,name=nid,proto3" json:"nid,omitempty"`
	Rid                  string   `protobuf:"bytes,3,opt,name=rid,proto3" json:"rid,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Mid                  string   `protobuf:"bytes,5,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3655907f88b3485, []int{0}
}

func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (m *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(m, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetDc() string {
	if m != nil {
		return m.Dc
	}
	return ""
}

func (m *Info) GetNid() string {
	if m != nil {
		return m.Nid
	}
	return ""
}

func (m *Info) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *Info) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *Info) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type Stream struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Tracks               []*Track `protobuf:"bytes,2,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Stream) Reset()         { *m = Stream{} }
func (m *Stream) String() string { return proto.CompactTextString(m) }
func (*Stream) ProtoMessage()    {}
func (*Stream) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3655907f88b3485, []int{1}
}

func (m *Stream) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Stream.Unmarshal(m, b)
}
func (m *Stream) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Stream.Marshal(b, m, deterministic)
}
func (m *Stream) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Stream.Merge(m, src)
}
func (m *Stream) XXX_Size() int {
	return xxx_messageInfo_Stream.Size(m)
}
func (m *Stream) XXX_DiscardUnknown() {
	xxx_messageInfo_Stream.DiscardUnknown(m)
}

var xxx_messageInfo_Stream proto.InternalMessageInfo

func (m *Stream) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Stream) GetTracks() []*Track {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type Track struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ssrc                 uint32   `protobuf:"varint,3,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	Payload              uint32   `protobuf:"varint,4,opt,name=payload,proto3" json:"payload,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Codec                string   `protobuf:"bytes,6,opt,name=codec,proto3" json:"codec,omitempty"`
	Fmtp                 string   `protobuf:"bytes,7,opt,name=fmtp,proto3" json:"fmtp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Track) Reset()         { *m = Track{} }
func (m *Track) String() string { return proto.CompactTextString(m) }
func (*Track) ProtoMessage()    {}
func (*Track) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3655907f88b3485, []int{2}
}

func (m *Track) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Track.Unmarshal(m, b)
}
func (m *Track) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Track.Marshal(b, m, deterministic)
}
func (m *Track) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Track.Merge(m, src)
}
func (m *Track) XXX_Size() int {
	return xxx_messageInfo_Track.Size(m)
}
func (m *Track) XXX_DiscardUnknown() {
	xxx_messageInfo_Track.DiscardUnknown(m)
}

var xxx_messageInfo_Track proto.InternalMessageInfo

func (m *Track) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Track) GetSsrc() uint32 {
	if m != nil {
		return m.Ssrc
	}
	return 0
}

func (m *Track) GetPayload() uint32 {
	if m != nil {
		return m.Payload
	}
	return 0
}

func (m *Track) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Track) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

func (m *Track) GetFmtp() string {
	if m != nil {
		return m.Fmtp
	}
	return ""
}

func init() {
	proto.RegisterType((*Info)(nil), "media.Info")
	proto.RegisterType((*Stream)(nil), "media.Stream")
	proto.RegisterType((*Track)(nil), "media.Track")
}

func init() { proto.RegisterFile("pkg/proto/media/media.proto", fileDescriptor_c3655907f88b3485) }

var fileDescriptor_c3655907f88b3485 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0x95, 0xbf, 0x15, 0x07, 0x45, 0xc8, 0x62, 0xb0, 0xc4, 0x52, 0x05, 0x90, 0x3a, 0x25,
	0x12, 0xec, 0x0c, 0x6c, 0xac, 0x81, 0x89, 0x01, 0xc9, 0xf5, 0xa5, 0xe5, 0x54, 0x1c, 0x5b, 0x8e,
	0x33, 0x74, 0xe6, 0x8b, 0x23, 0xfb, 0xda, 0x85, 0x0e, 0xb6, 0xde, 0xfb, 0xf9, 0x59, 0xf7, 0x74,
	0x70, 0xe7, 0xf6, 0xbb, 0xce, 0x79, 0x1b, 0x6c, 0x67, 0x06, 0x24, 0xc5, 0x77, 0x9b, 0x88, 0xa8,
	0x92, 0x69, 0xbe, 0xa0, 0x7c, 0x1b, 0xb7, 0x56, 0x5c, 0x43, 0x8e, 0x5a, 0x66, 0xab, 0x6c, 0x7d,
	0xd1, 0xe7, 0xa8, 0xc5, 0x0d, 0x14, 0x23, 0xa1, 0xcc, 0x13, 0x88, 0x32, 0x12, 0x4f, 0x28, 0x0b,
	0x26, 0x9e, 0xc9, 0x4c, 0x28, 0x4b, 0x26, 0x33, 0x13, 0x43, 0x28, 0x2b, 0x26, 0x86, 0xb0, 0x79,
	0x81, 0xfa, 0x3d, 0xf8, 0x41, 0x99, 0x38, 0x81, 0xf0, 0x34, 0x81, 0x50, 0x3c, 0x40, 0x1d, 0xbc,
	0xd2, 0xfb, 0x49, 0xe6, 0xab, 0x62, 0x7d, 0xf9, 0x74, 0xd5, 0x72, 0xbd, 0x8f, 0x08, 0xfb, 0xe3,
	0x5b, 0xf3, 0x9b, 0x41, 0x95, 0xc8, 0xd9, 0x7f, 0x01, 0xe5, 0x34, 0x79, 0x9d, 0x0a, 0x2d, 0xfb,
	0xa4, 0x85, 0x84, 0x85, 0x53, 0x87, 0x1f, 0xab, 0xb8, 0xd5, 0xb2, 0x3f, 0xd9, 0x98, 0x0e, 0x07,
	0x37, 0x1c, 0xab, 0x25, 0x2d, 0x6e, 0xa1, 0xd2, 0x16, 0x07, 0x2d, 0xeb, 0x04, 0xd9, 0xc4, 0xe4,
	0xd6, 0x04, 0x27, 0x17, 0x9c, 0x8c, 0xfa, 0xf5, 0xf1, 0xf3, 0x7e, 0x47, 0xe1, 0x7b, 0xde, 0xb4,
	0xda, 0x9a, 0xce, 0x91, 0x1d, 0xbb, 0x78, 0xfe, 0xed, 0x77, 0x53, 0x27, 0xf3, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x80, 0x82, 0x10, 0x7a, 0x79, 0x01, 0x00, 0x00,
}
